/**
 * 默认 meme 列表，可用于 MemeLoading 组件自定义
 */
export const defaultMemesSet = [
  '←→AB gocha',
  'E=MC²',
  'for (let i = 0; i < array.length; i++) { }',
  '"Hello, world!"',
  'function foo() { }',
  'let x = 10;',
  'const y = 20;',
  'import React from "react";',
  'PHP is the Best Language',
  'F=ma',
  'V=IR',
  'a² + b² = c²',
  'e^(iπ) + 1 = 0',
  'ΔE=Δmc²',
  '(^_^)',
  '(>_<)',
  '¯\\_(ツ)_/¯',
  '(¬‿¬)',
  'ಠ_ಠ',
  '(ง •̀_•́)ง',
  '(◕‿◕✿)',
  '༼ つ ◕_◕ ༽つ',
  'ಠ╭╮ಠ',
  'ʕ•ᴥ•ʔ',
  'Catch Them All',
  '注意安全',
  '带好安全帽',
  '黄+蓝=绿',
  '苟利国家生死已，岂因祸福避趋之',
  'Too Simple , Sometimes Naive !',
  'Chinese DOTA,Best DOTA!',
  'Free Free Palestine!',
  '不要忘记DL6号事件',
];
